version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: flaskdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development  # これによりデバッグモードが有効になる
      - FLASK_DEBUG=1  # デバッグモードを強制的にONにする
      - SECRET_KEY=your_very_secret_key 
    volumes:
      - .:/app

volumes:
  db_data:
